#!/bin/sh
set -e

if [ -z "$1" ]; then
    echo "Usage: $0 CONTAINER"
    exit 1
fi


FS=/var/lib/machines/$1/fs
TARGET=cloud-init
TARGET=basic

kostka mount $1
if [ ! -f $FS/etc/os-release ]; then
    echo "Empty filesystem - not booting."
    exit 0
fi

if [ ! -d $FS/lib/systemd/system/$TARGET.target ]; then
    # Fall back to basic.target
    TARGET=basic
fi

# install the poweroff service
mkdir -p $FS/etc/systemd/system
cat > $FS/etc/systemd/system/poweroff.service <<END
[Unit]
Description=Poweroff after first boot
After=default.target

[Service]
Type=oneshot
ExecStart=/bin/systemctl poweroff
END

echo $1 > $FS/etc/hostname

mkdir -p $FS/etc/systemd/system/$TARGET.target.wants
ln -s ../poweroff.service $FS/etc/systemd/system/$TARGET.target.wants/poweroff.service
cat /proc/sys/kernel/random/uuid | tr -d '-' > $FS/etc/machine-id

/usr/bin/systemd-nspawn --quiet --boot --directory=$FS -M $1 systemd.unit=$TARGET.target

rm $FS/etc/systemd/system/$TARGET.target.wants/poweroff.service
rm $FS/etc/systemd/system/poweroff.service
